In [18]:
#import dependencies
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
#read csv datasets and assign to variables
train_data = pd.read_csv("./Resources/Training.csv")
test_data = pd.read_csv("./Resources/Testing.csv")

In [20]:
train_data.head(10)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   
5        0          1                     1                    0          0   
6        1          0                     1                    0          0   
7        1          1                     0                    0          0   
8        1          1                     1                    0          0   
9        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   
5       0           0             0        0                 0  ...         0   
6       0           0             0        0                 0  ...         0   
7       0           0             0        0                 0  ...         0   
8       0           0             0        0                 0  ...         0   
9       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   
5             0                    0                     0   
6             0                    0                     0   
7             0                    0                     0   
8             0                    0                     0   
9             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   
5                   0        0                     0                  0   
6                   0        0                     0                  0   
7                   0        0                     0                  0   
8                   0        0                     0                  0   
9                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  
5  Fungal infection           NaN  
6  Fungal infection           NaN  
7  Fungal infection           NaN  
8  Fungal infection           NaN  
9  Fungal infection           NaN  

[10 rows x 134 columns]

In [21]:
test_data.head(10)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   
5        0          0                     0                    0          0   
6        0          0                     0                    0          0   
7        0          0                     0                    0          0   
8        0          0                     0                    0          0   
9        0          0                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   
5       0           0             0        0                 0  ...   
6       0           0             0        0                 0  ...   
7       0           0             0        0                 0  ...   
8       0           0             0        0                 0  ...   
9       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   
5           0         0             0                    0   
6           0         0             0                    0   
7           0         0             0                    0   
8           0         0             0                    0   
9           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   
5                     0                   0        0                     0   
6                     0                   0        0                     0   
7                     0                   0        0                     0   
8                     0                   0        0                     0   
9                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  
5                  0  Peptic ulcer diseae  
6                  0                 AIDS  
7                  0            Diabetes   
8                  0      Gastroenteritis  
9                  0     Bronchial Asthma  

[10 rows x 133 columns]

In [22]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 134 entries, itching to Unnamed: 133
dtypes: float64(1), int64(132), object(1)
memory usage: 5.0+ MB


In [23]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 43.8+ KB


In [24]:
train_data.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...   blackheads     scurring  skin_peeling  \
count       4920.000000  ...  4920.000000  4920.000000   4920.000000   
mean           0.021951  ...     0.021951     0.021951      0.023171   
std            0.146539  ...     0.146539     0.146539      0.150461   
min            0.000000  ...     0.000000     0.000000      0.000000   
25%            0.000000  ...     0.000000     0.000000      0.000000   
50%            0.000000  ...     0.000000     0.000000      0.000000   
75%            0.000000  ...     0.000000     0.000000      0.000000   
max            1.000000  ...     1.000000     1.000000      1.000000   

       silver_like_dusting  small_dents_in_nails  inflammatory_nails  \
count          4920.000000           4920.000000         4920.000000   
mean              0.023171              0.023171            0.023171   
std               0.150461              0.150461            0.150461   
min               0.000000              0.000000            0.000000   
25%               0.000000              0.000000            0.000000   
50%               0.000000              0.000000            0.000000   
75%               0.000000              0.000000            0.000000   
max               1.000000              1.000000            1.000000   

           blister  red_sore_around_nose  yellow_crust_ooze  Unnamed: 133  
count  4920.000000           4920.000000        4920.000000           0.0  
mean      0.023171              0.023171           0.023171           NaN  
std       0.150461              0.150461           0.150461           NaN  
min       0.000000              0.000000           0.000000           NaN  
25%       0.000000              0.000000           0.000000           NaN  
50%       0.000000              0.000000           0.000000           NaN  
75%       0.000000              0.000000           0.000000           NaN  
max       1.000000              1.000000           1.000000           NaN  

[8 rows x 133 columns]

In [25]:
test_data.describe()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  42.000000  42.000000             42.000000            42.000000   
mean    0.166667   0.190476              0.023810             0.047619   
std     0.377195   0.397437              0.154303             0.215540   
min     0.000000   0.000000              0.000000             0.000000   
25%     0.000000   0.000000              0.000000             0.000000   
50%     0.000000   0.000000              0.000000             0.000000   
75%     0.000000   0.000000              0.000000             0.000000   
max     1.000000   1.000000              1.000000             1.000000   

       shivering     chills  joint_pain  stomach_pain    acidity  \
count  42.000000  42.000000   42.000000     42.000000  42.000000   
mean    0.023810   0.166667    0.142857      0.047619   0.047619   
std     0.154303   0.377195    0.354169      0.215540   0.215540   
min     0.000000   0.000000    0.000000      0.000000   0.000000   
25%     0.000000   0.000000    0.000000      0.000000   0.000000   
50%     0.000000   0.000000    0.000000      0.000000   0.000000   
75%     0.000000   0.000000    0.000000      0.000000   0.000000   
max     1.000000   1.000000    1.000000      1.000000   1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples  blackheads   scurring  \
count         42.000000  ...           42.000000   42.000000  42.000000   
mean           0.023810  ...            0.023810    0.023810   0.023810   
std            0.154303  ...            0.154303    0.154303   0.154303   
min            0.000000  ...            0.000000    0.000000   0.000000   
25%            0.000000  ...            0.000000    0.000000   0.000000   
50%            0.000000  ...            0.000000    0.000000   0.000000   
75%            0.000000  ...            0.000000    0.000000   0.000000   
max            1.000000  ...            1.000000    1.000000   1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count     42.000000            42.000000             42.000000   
mean       0.047619             0.023810              0.023810   
std        0.215540             0.154303              0.154303   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails    blister  red_sore_around_nose  yellow_crust_ooze  
count           42.000000  42.000000             42.000000          42.000000  
mean             0.023810   0.023810              0.047619           0.023810  
std              0.154303   0.154303              0.215540           0.154303  
min              0.000000   0.000000              0.000000           0.000000  
25%              0.000000   0.000000              0.000000           0.000000  
50%              0.000000   0.000000              0.000000           0.000000  
75%              0.000000   0.000000              0.000000           0.000000  
max              1.000000   1.000000              1.000000           1.000000  

[8 rows x 132 columns]

In [27]:
# checking for testing set
for col in list(test_data.columns):
    print('-'*35 + col + '-' * 35 , end='*')
    display(test_data[col].unique())

-----------------------------------itching-----------------------------------*

array([1, 0], dtype=int64)

-----------------------------------skin_rash-----------------------------------*

array([1, 0], dtype=int64)

-----------------------------------nodal_skin_eruptions-----------------------------------*

array([1, 0], dtype=int64)

-----------------------------------continuous_sneezing-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------shivering-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------chills-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------joint_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------stomach_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------acidity-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------ulcers_on_tongue-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------muscle_wasting-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------vomiting-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------burning_micturition-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------spotting_ urination-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------fatigue-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------weight_gain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------anxiety-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------cold_hands_and_feets-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------mood_swings-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------weight_loss-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------restlessness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------lethargy-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------patches_in_throat-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------irregular_sugar_level-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------cough-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------high_fever-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------sunken_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------breathlessness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------sweating-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------dehydration-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------indigestion-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------headache-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------yellowish_skin-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------dark_urine-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------nausea-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------loss_of_appetite-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------pain_behind_the_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------back_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------constipation-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------abdominal_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------diarrhoea-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------mild_fever-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------yellow_urine-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------yellowing_of_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------acute_liver_failure-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------fluid_overload-----------------------------------*

array([0], dtype=int64)

-----------------------------------swelling_of_stomach-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------swelled_lymph_nodes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------malaise-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------blurred_and_distorted_vision-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------phlegm-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------throat_irritation-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------redness_of_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------sinus_pressure-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------runny_nose-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------congestion-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------chest_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------weakness_in_limbs-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------fast_heart_rate-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------pain_during_bowel_movements-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------pain_in_anal_region-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------bloody_stool-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------irritation_in_anus-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------neck_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------dizziness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------cramps-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------bruising-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------obesity-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------swollen_legs-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------swollen_blood_vessels-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------puffy_face_and_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------enlarged_thyroid-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------brittle_nails-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------swollen_extremeties-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------excessive_hunger-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------extra_marital_contacts-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------drying_and_tingling_lips-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------slurred_speech-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------knee_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------hip_joint_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------muscle_weakness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------stiff_neck-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------swelling_joints-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------movement_stiffness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------spinning_movements-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------loss_of_balance-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------unsteadiness-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------weakness_of_one_body_side-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------loss_of_smell-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------bladder_discomfort-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------foul_smell_of urine-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------continuous_feel_of_urine-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------passage_of_gases-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------internal_itching-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------toxic_look_(typhos)-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------depression-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------irritability-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------muscle_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------altered_sensorium-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------red_spots_over_body-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------belly_pain-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------abnormal_menstruation-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------dischromic _patches-----------------------------------*

array([1, 0], dtype=int64)

-----------------------------------watering_from_eyes-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------increased_appetite-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------polyuria-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------family_history-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------mucoid_sputum-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------rusty_sputum-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------lack_of_concentration-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------visual_disturbances-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------receiving_blood_transfusion-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------receiving_unsterile_injections-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------coma-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------stomach_bleeding-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------distention_of_abdomen-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------history_of_alcohol_consumption-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------fluid_overload.1-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------blood_in_sputum-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------prominent_veins_on_calf-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------palpitations-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------painful_walking-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------pus_filled_pimples-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------blackheads-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------scurring-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------skin_peeling-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------silver_like_dusting-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------small_dents_in_nails-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------inflammatory_nails-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------blister-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------red_sore_around_nose-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------yellow_crust_ooze-----------------------------------*

array([0, 1], dtype=int64)

-----------------------------------prognosis-----------------------------------*

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [28]:
#isolate columns with null data
train_data.isnull().any()

itching                 False
skin_rash               False
nodal_skin_eruptions    False
continuous_sneezing     False
shivering               False
                        ...  
blister                 False
red_sore_around_nose    False
yellow_crust_ooze       False
prognosis               False
Unnamed: 133             True
Length: 134, dtype: bool

In [29]:
#"Unnamed:133" column is unclean and contains null data, drop it
train_data.drop(["Unnamed: 133"], axis=1, inplace=True)

In [30]:
train_data

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [31]:
train_data.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [32]:
train_data.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [33]:
train_data["prognosis"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [34]:
#split dataset into attributes and labels
X_train = train_data.iloc[:,:-1].values # the training attributes
y_train = train_data.iloc[:,132].values # the training labels
X_test = test_data.iloc[:,:-1].values # the testing attributes
y_test = test_data.iloc[:,132].values # the testing labels
print("X_trainshape: ",X_train.shape,"y_train_shape: ", y_train.shape)
print("X_test.shape: ", X_test.shape,"y_test.shape: ", y_test.shape)

X_trainshape:  (4920, 132) y_train_shape:  (4920,)
X_test.shape:  (42, 132) y_test.shape:  (42,)
